name: actions-build-on-push 

on:
  push:
    branches: [ "master" ]

jobs:
  runs-on: ubuntu-latest
  build:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install 
      - run: npm run build

  deploy:
    steps:
      - name: install dependencies 
        run: npm install 
      - run: npm run build
      - run: netlify deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir build/ --prod
