name: actions-build-on-push
on:
  push:
    branches: [ "master" ]

jobs:
  action-buildon-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install 
      - run: npm run build
